-- Add construction and engineering terms organized by discipline
INSERT INTO public.glossary_terms (en, kr, description, discipline, abbreviation, status) VALUES

-- Civil (토목)
('Screed', '스크리드', '바닥이나 다른 표면에 적용되는 콘크리트와 같은 평평한 재료 층', 'Civil', 'Civil', 'approved'),
('Contraction/Control Joint', '수축 조인트', '', 'Civil', 'Civil', 'approved'),
('Saw Cut', '쏘컷', '', 'Civil', 'Civil', 'approved'),
('Base Layer', '기층', '', 'Civil', 'Civil', 'approved'),
('Flatness, FF', '평탄도, 평활도', '', 'Civil', 'Civil', 'approved'),
('Levelness, FL', '수평도', '', 'Civil', 'Civil', 'approved'),
('Self Levelling', '자체평활', '', 'Civil', 'Civil', 'approved'),
('Penetrating Sealer', '침투성 실러', '', 'Civil', 'Civil', 'approved'),
('Binder', '결합재', '콘크리트 결합재', 'Civil', 'Civil', 'approved'),
('Blasting', '연마', '', 'Civil', 'Civil', 'approved'),
('Low Lying Area', '저지대', '', 'Civil', 'Civil', 'approved'),
('Plinth', '주추', '건축에서 기둥, 상, 기념비 등의 받침대', 'Civil', 'Civil', 'approved'),
('Square Driven Pile', '사각 항타 파일', '', 'Civil', 'Civil', 'approved'),
('Circular Bored Pile', '원형 보드 파일', '', 'Civil', 'Civil', 'approved'),
('Gravity Flow', '자연구배, 중력류, 자연유하식', '', 'Civil', 'Civil', 'approved'),
('Environmental Impact Assessment', '환경영향평가', '', 'Civil', 'Civil', 'approved'),
('Setback Requirement', '이격거리 기준', '', 'Civil', 'Civil', 'approved'),
('BOQ, Bill of Quantities', '공사내역서', '', 'Civil', 'Civil', 'approved'),
('Construction Daily Log', '공사일보', '', 'Civil', 'Civil', 'approved'),
('Deep Underground', '대심도 지하', '', 'Civil', 'Civil', 'approved'),

-- Architecture (건축)
('Inlet Grill', '흡입그릴', '', 'Architecture', 'Arch', 'approved'),
('Outlet Grill', '토출그릴', '', 'Architecture', 'Arch', 'approved'),
('Castor Chair', '바퀴 의자', '', 'Architecture', 'Arch', 'approved'),
('Solventless', '무용제', '', 'Architecture', 'Arch', 'approved'),
('Slip-Resistance', '미끄럼 저항성', '', 'Architecture', 'Arch', 'approved'),
('Landing Area', '계단참, 층계참', '계단의 계단참, 경사로의 층계참', 'Architecture', 'Arch', 'approved'),
('Planter Box', '화분', '', 'Architecture', 'Arch', 'approved'),
('A Flight of Stairs', '한 층을 올라가는 계단', 'Ten flights of stairs: 계단 10층', 'Architecture', 'Arch', 'approved'),
('Step On', '침범하다', '', 'Architecture', 'Arch', 'approved'),
('Tile Joint', '타일 줄눈', '', 'Architecture', 'Arch', 'approved'),
('Sanitary Fitting', '위생 설비', '', 'Architecture', 'Arch', 'approved'),
('Suspended Ceiling', '매달린 천장, 반자', '', 'Architecture', 'Arch', 'approved'),
('Lift Shaft', '승강기 통로, 승강로', '', 'Architecture', 'Arch', 'approved'),
('Tabletop', '탁상형', '', 'Architecture', 'Arch', 'approved'),
('Standing Machine', '스탠드형', '', 'Architecture', 'Arch', 'approved'),
('Aerated Tap', '통기 수전', '', 'Architecture', 'Arch', 'approved'),
('Intercom', '인터폰', '', 'Architecture', 'Arch', 'approved'),
('Turnstile', '회전문', '', 'Architecture', 'Arch', 'approved'),
('Heat Gain', '열획득', '', 'Architecture', 'Arch', 'approved'),
('Heat Loss', '열손실', '', 'Architecture', 'Arch', 'approved'),
('Detailing', '세부 장식', '건물, 의류 등에 붙이는 세부 장식', 'Architecture', 'Arch', 'approved'),
('Metal Backed Fabric', '금속 배면 직물', '', 'Architecture', 'Arch', 'approved'),
('Ironmongery', '철물', '', 'Architecture', 'Arch', 'approved'),
('Deterioration', '열화', '', 'Architecture', 'Arch', 'approved'),
('Construction Document', '시공 도서', '', 'Architecture', 'Arch', 'approved'),
('Statement of Compliance', '준수 진술서', '', 'Architecture', 'Arch', 'approved'),
('Certificate of Occupancy', '사용승인', '', 'Architecture', 'Arch', 'approved'),
('Record Drawing', '준공도면', '', 'Architecture', 'Arch', 'approved'),
('Architecture Planning Approval', '계획허가', '', 'Architecture', 'Arch', 'approved'),
('Basic Design Drawing', '기본설계도면', '', 'Architecture', 'Arch', 'approved'),
('Basic Design Assessment', '기본설계평가', '', 'Architecture', 'Arch', 'approved'),
('Construction Design Drawing', '시공설계도면', '', 'Architecture', 'Arch', 'approved'),
('Construction Design Assessment', '기술설계심의', '', 'Architecture', 'Arch', 'approved'),
('Construction Approval', '건설허가', '', 'Architecture', 'Arch', 'approved'),
('Construction As-built Approval', '건설준공허가', '', 'Architecture', 'Arch', 'approved'),
('High-Piled Storage', '고적재 저장소', '', 'Architecture', 'Arch', 'approved'),
('Single Family Dwelling, SFD', '단독주택', '', 'Architecture', 'Arch', 'approved'),
('Two Family Dwelling', '2가구 주택', '', 'Architecture', 'Arch', 'approved'),
('Mechanical Access Enclosed Parking Garage', '기계식 실내주차장', '', 'Architecture', 'Arch', 'approved'),
('Clear Opening', '개구치수', '', 'Architecture', 'Arch', 'approved'),
('Covered Building', '폐쇄형 건물', '', 'Architecture', 'Arch', 'approved'),
('Open Building', '개방형 건물', '', 'Architecture', 'Arch', 'approved'),
('Tenant Space', '임대공간', '', 'Architecture', 'Arch', 'approved'),
('Breezeway', '옥외 통로', '떨어진 건물 사이를 잇는, 지붕을 얹은 옥외 통로', 'Architecture', 'Arch', 'approved'),
('Multiple Exits', '다중 출구', '', 'Architecture', 'Arch', 'approved'),
('Shop Drawing', '시공 상세도', '', 'Architecture', 'Arch', 'approved'),

-- Fire Protection (소방)
('Fog Nozzle', '무상노즐', '미세한 분무나 안개형태로 물을 방출하는 노즐', 'Fire Protection', 'FP', 'approved'),
('Deluge System', '일제살수식 설비', '', 'Fire Protection', 'FP', 'approved'),
('Mineral(Rock) Wool', '미네랄울', '', 'Fire Protection', 'FP', 'approved'),
('Fire Area', '방화구획', '', 'Fire Protection', 'FP', 'approved'),
('Horizontal Assembly', '수평 조립체', '', 'Fire Protection', 'FP', 'approved'),
('Fire Apparatus', '소방차', '', 'Fire Protection', 'FP', 'approved'),
('Fire Apparatus Operator', '소방차 운전자', '', 'Fire Protection', 'FP', 'approved'),
('Water-Based Fire Protection System', '수계소화설비', '', 'Fire Protection', 'FP', 'approved'),
('Water Mist System', '미분무수 설비', '', 'Fire Protection', 'FP', 'approved'),
('Impairment', '장애', '', 'Fire Protection', 'FP', 'approved'),
('Fire Department Connection', '연결송수구', '', 'Fire Protection', 'FP', 'approved'),
('Fire Alarm Annunciator', '수신기, 경보표시기', '', 'Fire Protection', 'FP', 'approved'),
('Occupant Use Hose', '거주자용 호스', '훈련된 소방관 또는 소방대원이 도착하기 전에 건물의 거주자가 초기화재를 진압하기 위해 사용하는 호스', 'Fire Protection', 'FP', 'approved'),
('Alarm Signal', '경보신호', '', 'Fire Protection', 'FP', 'approved'),
('Annunciator', '시각신호 표시기', '회로, 위치에 대한 상태 정보를 제공하고 2 이상의 표시램프, 문자표시, 기타 이와 동등한 설비를 포함하는 유닛', 'Fire Protection', 'FP', 'approved'),
('Attended Facility', '유인시설', '', 'Fire Protection', 'FP', 'approved'),
('Unattended Facility', '무인시설', '', 'Fire Protection', 'FP', 'approved'),
('Alarm Box', '경보발신기', '', 'Fire Protection', 'FP', 'approved'),
('Halogenated Extinguishing System', '할론소화설비', '', 'Fire Protection', 'FP', 'approved'),
('Multiple Station Alarm Device', '다중(연동)경보장치', '', 'Fire Protection', 'FP', 'approved'),
('Pumping', '양수', '', 'Fire Protection', 'FP', 'approved'),
('Unwanted Alarm', '비화재보', '화재에 의한 열, 연기 또는 불꽃(화염)이외의 요인에 의하여 자동화재탐지설비가 작동하여 화재경보를 발하는 것', 'Fire Protection', 'FP', 'approved'),
('Nuisance Alarm', '일과성 비화재보', '주위상황이 대부분 순간적으로 화재와 같은 상태(실재 화재와 유사한 환경이나 상황)로 되었다가 정상상태로 복귀하는 경우', 'Fire Protection', 'FP', 'approved'),
('Single Station Alarm Device', '단신호식 경보장치', '', 'Fire Protection', 'FP', 'approved'),
('Smoke Alarm', '연기경보기', '', 'Fire Protection', 'FP', 'approved'),
('Supervising Station', '감시실', '', 'Fire Protection', 'FP', 'approved'),
('Supervisory Service', '감시업무', '', 'Fire Protection', 'FP', 'approved'),
('Supervisory Signal', '감시신호', '', 'Fire Protection', 'FP', 'approved'),
('Fire Fighting Approval', '소방허가', '', 'Fire Protection', 'FP', 'approved'),
('Fire Fighting As-built Approval', '소방준공', '', 'Fire Protection', 'FP', 'approved'),
('Dip Tank', '침지탱크', '', 'Fire Protection', 'FP', 'approved'),
('Hardening', '경화', '', 'Fire Protection', 'FP', 'approved'),
('Tempering', '담금질', '', 'Fire Protection', 'FP', 'approved'),
('Loose Fiber', '원모', '', 'Fire Protection', 'FP', 'approved'),
('Highly Toxic', '고독성', '', 'Fire Protection', 'FP', 'approved'),
('Very Highly Toxic', '맹독성', '', 'Fire Protection', 'FP', 'approved'),
('Thermal Barrier Rating', '열차폐등급', '', 'Fire Protection', 'FP', 'approved'),
('Limited Combustible Material', '준불연재료', '', 'Fire Protection', 'FP', 'approved'),
('Smoke Compartment', '방연구획', '', 'Fire Protection', 'FP', 'approved'),
('Hydraulic Calculation', '관경 선정', '배관 내에서 유동하는 유체의 특성을 파악하고 이의 특성을 기준으로 관내에서 최적조건, 즉 경제성과 운전성, 을 고려하여 관의 크기를 결정하는 것', 'Fire Protection', 'FP', 'approved'),
('Jockey Pump', '충압펌프', '', 'Fire Protection', 'FP', 'approved'),
('Distinctive Signal', '다종음향경보', '', 'Fire Protection', 'FP', 'approved'),
('Discharge Orifice', '방출구', '', 'Fire Protection', 'FP', 'approved'),
('Stored Pressure Type', '축압식', '소화기', 'Fire Protection', 'FP', 'approved'),
('Fusible Link', '퓨저블 링크', '', 'Fire Protection', 'FP', 'approved'),
('Liquid Level Gauge', '액위계', '', 'Fire Protection', 'FP', 'approved'),
('Hand Hose Line System', '호스릴설비', '', 'Fire Protection', 'FP', 'approved'),
('Floor Control Valve', '층 제어밸브', '', 'Fire Protection', 'FP', 'approved'),

-- Piping (배관)
('Face-to-Face Dimension', '면간 치수', '', 'Piping', 'Piping', 'approved'),
('Bevel Processing', '개선가공', '', 'Piping', 'Piping', 'approved'),
('Check Valve', '역지밸브', '펌프의 정지나 계통의 과도 시 계통의 유동 역류를 방지하고 유동을 한 방향으로만 유지시키는 하나의 부품으로서 전기 회로 내의 다이오드(한 방향으로의 이동을 지원)와 같은 역할을 함', 'Piping', 'Piping', 'approved'),
('Reducing Flange', '리듀싱 플랜지', '', 'Piping', 'Piping', 'approved'),
('Blind Flange', '맹플랜지', '', 'Piping', 'Piping', 'approved'),
('Malleable Cast Iron', '가단주철', '', 'Piping', 'Piping', 'approved'),
('Same Size', '동경치수', '', 'Piping', 'Piping', 'approved'),
('Reduced Size', '이경치수', '', 'Piping', 'Piping', 'approved'),

-- Structure (구조)
('Stationary Equipment', '고정식 장비', '', 'Structure', 'Struct', 'approved'),
('Rotating Machinery', '회전기기', '', 'Structure', 'Struct', 'approved'),
('Acceptance Test', '인수테스트', '', 'Structure', 'Struct', 'approved'),
('Powered Industrial Truck', '동력 산업용 트럭', '', 'Structure', 'Struct', 'approved'),

-- HVAC (공조)
('Air Velocity', '풍속', '', 'HVAC', 'HVAC', 'approved'),

-- 프로젝트 일반 용어 (General Project Terms)
('Cyber Defense Center', '사이버 방위센터', '', '프로젝트 일반 용어', 'Gen', 'approved'),
('Physical Security', '물리 보안', '', '프로젝트 일반 용어', 'Gen', 'approved'),
('Hostile Vehicle Mitigation', '적대적 차량 완화', '', '프로젝트 일반 용어', 'Gen', 'approved'),
('Emergency Vehicle', '비상차량', '', '프로젝트 일반 용어', 'Gen', 'approved'),
('Proof of Quality', '품질증명', '', '프로젝트 일반 용어', 'Gen', 'approved'),
('Process Capability Report', '공정 능력 보고서', '', '프로젝트 일반 용어', 'Gen', 'approved'),
('Standard Organization', '표준화 기구', '', '프로젝트 일반 용어', 'Gen', 'approved')

ON CONFLICT (en, kr) DO NOTHING;
