-- Delete the engineering terms that were previously added
-- This script removes the specific terms from the glossary table

DELETE FROM public.glossary_terms WHERE en IN (
  'Basic Engineering Design Data, BEDD',
  'Issued For Approval, IFA',
  'Approval for Construction, AFC',
  'Detail Design Engineering, DDE',
  'Letter of Intent, L/I',
  'Piping and Instrument Diagram, P&ID',
  'Invitation to Bid, ITB',
  'Technical Bid Evaluation, TBE',
  'Technical Bid Analysis, TBA',
  'Commercial Bid Analysis, CBA',
  'Fire Fighting, F/F',
  'Document Control Log, DCL',
  'Process Flow Diagram, PFD',
  'Distributed Control System, DCS',
  'Quality Assurance Representative, QAR',
  'Design Review Request, DRR',
  'Design Review Check-List, DRL',
  'Master Document Control Log, MDCL',
  'Heating, Ventilation and Air Conditioning, HVAC',
  'Fuel Test Loop, FTL',
  'Engineering Procurement Construction, EPC',
  'Engineering Procurement Construction Inspection, EPCI',
  'In Site Battery Limit, ISBL',
  'Out Site Battery Limit, OSBL',
  'Request For Quotation, RFQ',
  'Primary Feasibility Study Report, PFS',
  'Feasibility Study Report, FSR',
  'Basic Design Report, BDR',
  'Project Engineering/Design Execution Plan, PDP',
  'Project Execution Plan, EDP',
  'System Design Criteria, SDC',
  'Technical Specification & Data Sheet, TSP',
  'System Design Description, SDD',
  'Construction Specification, CSP',
  'Miscellaneous Engineering Procedure, ZEP',
  'Cost Estimation for Construction, CES',
  'Preliminary Design Review Report, PDR',
  'Final Design Report, FDR',
  'List, LST',
  'Bill of Material, BOM',
  'Data Sheet, DSH',
  'Inspection or Test Sheets, ISH',
  'Check List or Punch List, CHL',
  'Test Report, TRT',
  'Calculation, CAL',
  'Contractor''s Master Document Register, CDMR',
  'Project Cost Control Sheet, PCCS',
  'Combined Heat & Power, CHP',
  'Hazards & Operability Study, HAZOP',
  'Process Safety Management, PSM',
  'Safety Management System, SMS',
  'Pile Location Plan, PLP',
  'Foundation Location Plan, FLP',
  'Engineering Master Document Schedule, EMD',
  'Pre-Qualification, PQ',
  'Platform, P/F',
  'Engineering Drawing, ENDO',
  'Underground, U/G',
  'Material Requisition, MR',
  'Transformer, TR',
  'Vendor Print, VP',
  'Battery Limit, BL',
  'Motor Control Center, MCC',
  'Minutes of Meeting, MOM',
  'Field Change Notice, FCN',
  'Field Change Request, FCR',
  'Design Change Notice, DCN',
  'Design Change Request, DCR',
  'Project Manager, PM',
  'Project Coordinator, PC',
  'Lead Engineer, LE',
  'Assign Engineer, AE',
  'Interdisciplinary Design Review, IDR',
  'Turbine Generator, T/G',
  'Purchase Order, P/O',
  'Mechanical Completion, M/C',
  'Master Engineering Document List, MEDL',
  'Maximum Continuous Rating, MCR',
  'On-Line Monitoring System, OLMS',
  'As Soon As Possible, ASAP',
  'Joint Venture, J/V',
  'Build-Operate-Transfer, BOT',
  'Project Financing, PF',
  'Independent Power Producer, IPP',
  'Architectural Institute of Korea, AIK',
  'Tonnage of Oil Equivalent, TOE',
  'Division of Responsibility, DOR'
);

-- Also delete any terms that might have been added with similar Korean translations
DELETE FROM public.glossary_terms WHERE kr IN (
  '기본설계자료',
  '승인용 발행',
  '건설승인',
  '상세설계',
  '발주의향서',
  '공정 배관 계통도',
  '입찰안내서',
  '기술입찰평가',
  '기술입찰분석',
  '상업입찰분석',
  '소방',
  '문서관리목록',
  '공정흐름도',
  '분산제어시스템',
  '품질보증담당자',
  '설계검토 요청서',
  '설계검토 점검표',
  '총괄 문서관리 목록표',
  '난방, 통기, 공기조절',
  '핵연료 노내조사시험설비',
  '설계, 구매, 시공 일괄도급방식',
  '설계, 구매, 시공, 검사 일괄도급방식',
  '부지내 배터리 한계',
  '부지외 배터리 한계',
  '견적요청서',
  '예비 타당성 조사',
  '타당성 조사',
  '기본 설계 보고서',
  '설계계획서',
  '사업계획서',
  '계통 설계기준서',
  '기술사양서',
  '계통설계설명서',
  '공사시방서',
  '각종절차서',
  '공사설계서',
  '사전검토서',
  '최종설계보고서',
  '각종 목록',
  '수량산출',
  '데이터시트',
  '검사 또는 시험서',
  '점검목록',
  '시험보고서',
  '설계계산서',
  '계약자 주요문서 등록부',
  '프로젝트 비용관리표',
  '열병합발전',
  '위험성평가',
  '공정안전보고서',
  '안전성향계획서',
  '파일위치도',
  '기초위치도',
  '설계 주요문서 일정표',
  '사전자격심사',
  '플랫폼',
  '설계도면',
  '지하',
  '변압기',
  '업체도면',
  '배터리 한계',
  '전동기 제어반',
  '회의록',
  '현장 변경 통보',
  '현장 변경 요청',
  '설계 변경 통보',
  '설계 변경 요청',
  '프로젝트 관리자',
  '프로젝트 조정자',
  '주임기술자',
  '담당기술자',
  '분야간 설계 검토',
  '터빈발전기',
  '구매주문서',
  '기계준공',
  '설계 주요문서 목록',
  '시간당 최대열생산부하',
  '개별 감시 시스템',
  '가능한 빨리',
  '합작방식',
  '건설-운영-이양',
  '프로젝트 파이낸싱',
  '민간발전사업',
  '대한건축학회',
  '석유환산톤',
  '상세역무표'
);

-- Show the count of remaining terms after deletion
SELECT 
  COUNT(*) as remaining_terms,
  COUNT(CASE WHEN status = 'approved' THEN 1 END) as approved_terms,
  COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending_terms
FROM public.glossary_terms;

-- Show remaining terms by discipline
SELECT 
  discipline,
  COUNT(*) as term_count,
  COUNT(CASE WHEN status = 'approved' THEN 1 END) as approved,
  COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending
FROM public.glossary_terms 
GROUP BY discipline 
ORDER BY discipline;
